In [ ]:
print("hello world")

hello world


In [ ]:
x=15
y=4
print('x//y=',x/y)

x//y= 3.75


In [ ]:
x=15
y=4
print('x**y=',x**y)

x**y= 50625


In [ ]:
x=15
y=4
print('x//y=',x//y)

x//y= 3


In [ ]:
x=15
y=4
print('x%y=',x%y)

x%y= 3


In [ ]:
x=15
y=4
print('2x=',x-y+x+y)

2x= 30


In [ ]:
x=10
y=12
print(x!=y)
print(x<=y)
print(x>y)
print(x==y)

True
True
False
False


In [ ]:
List = ["Geeks", "For", "Geeks"] 
print("\nList containing multiple values: ") 
print(List)


List containing multiple values: 
['Geeks', 'For', 'Geeks']


In [ ]:
Dict = {'Name': 'Geeks', 1: [1, 2, 3, 4]}
print("Creating Dictionary: ")
print(Dict)
Tuple = ('Geeks', 'For')
print("\nTuple with the use of String: ")
print(Tuple)

Creating Dictionary: 
{'Name': 'Geeks', 1: [1, 2, 3, 4]}

Tuple with the use of String: 
('Geeks', 'For')


In [ ]:
Set = set([1, 2, 'Geeks', 4, 'For', 6, 'Geeks']) 
print("\nSet with the use of Mixed Values") 
print(Set) 


Set with the use of Mixed Values
{1, 2, 4, 6, 'Geeks', 'For'}


In [ ]:
x=True
y=False
print(x or y, not x, not y, x and y)

True False True False


In [ ]:
String = "Welcome"
print("Creating String: ") 
print(String)
print(String[0], String[-1]) 

Creating String: 
Welcome
W e


In [ ]:
s = "Python is great and Java is also great"
l = s.split()
k = []
for i in l:
    # If condition is used to store unique string
    # in another list 'k'
    if (s.count(i)>=1 and (i not in k)):
        k.append(i)
print(' '.join(k))

Python is great and Java also


In [ ]:
x=True
y=False
print(x or y, not x, not y, x and y)

True False True False


In [ ]:
x=10
y=4
print(.format(x), .format(y))

SyntaxError: invalid syntax (2931312477.py, line 3)

In [ ]:
x=10
y=4
print(binary={:b}.format(x))

SyntaxError: invalid syntax (3612503501.py, line 3)

In [ ]:
x=10
y=4
print('x value in binary={:b}'.format(x))

x value in binary=1010


In [ ]:
x=10
y=4
print('{:b}'.format(x))

1010


In [ ]:
x=10
y=4
print('{0:d},{0:b}'.format(x&y), '{0:d},{0:b}'.format(x|y),'{0:d},{0:b}'.format(x^y),'{0:d},{0:b}'.format(x>>2),'{0:d},{0:b}'.format(x<<2), '{0:d},{0:b}'.format(~x))

0,0 14,1110 14,1110 2,10 40,101000 -11,-1011


In [ ]:
x=10
y=4
print('decimal={0:d}, binary={0:b}'.format(x>>2))

decimal=2, binary=10


In [ ]:
x=10
y=4
print('decimal={0:d}, binary={0:b}'.format(x&y))

decimal=0, binary=0


In [ ]:
x=107
x+=3
print('x+=3 value :{0:d}'.format(x))
x*=3
print('{0:d}'.format(x))
x**=3
print('value={0:d}'.format(x))
#assignment operators are not applicable for bitwise operations

x+=3 value :110
330
value=35937000


In [ ]:
x1=5
y1=5
x2='Hello'
y2='Hello'
x3=[1,2,3]
y3=[1,2,3]
print(x1 is not y1)
print(x2 is not y2)
print(x not in y3)
#lists are same but not identical
print(x3 is not y1)

False
False
True
True


In [ ]:
x='Hello World'
y={1:'a', 2:'b'}
print('H' in x)
print('Hello' in x)
print(1 in y)
print('a' in y)

True
True
True
False


In [ ]:
x=10
y=5
z=15
print('decimal={0:d}, binary={0:b}, octal={0:o}, hexadecimal={0:x}'.format(z))

decimal=15, binary=1111, octal=17, hexadecimal=f


In [ ]:
x=10
y=5
print(x+y,x-y,x*y,x%y,x/y)

15 5 50 0 2.0


In [ ]:
print(234+788)
print(765-213)
print(4243*331)
print(12&13)
print(23|24)
print(100^21)
print(5>>2)
print(125<<2)

1022
552
1404433
12
31
113
1
500


In [ ]:
x=input('enter a number ')
x=int(x)
if(x>0):
    print('Positive')
else:
    print('Negative')
    
print('Thank you')

enter a number 20
Positive
Thank you


In [ ]:
name=input("enter your name ")
age=input("enter your age ")
salary=int(input("enter your salary "))
print("Name is :",name)
print("Age is :",age)
print("Salary is :",salary)
print("Annual salary :",salary*12)


enter your name x
enter your age 25
enter your salary 200000
Name is : x
Age is : 25
Salary is : 200000
Annual salary : 2400000


In [ ]:
name=input("enter your name ")
age=input("enter your age ")
salary=input("enter your salary ")
print("Name is :",name)
print("Age is :",age)
print("Salary is :",salary)
print("Annual salary :",salary*12)

In [ ]:
age=int(input("Enter age "))
if(age>=18):
    print("Eligible for voting")
else:
    print("Not eligible for voting")

Enter age 55
Eligible for voting


In [ ]:
num=int(input("Enter a number "))
if num>0:
    if num==0:
        print("Zero")
    else:
        print("Positive")
else:
    print("Negative number")

Enter a number 99
Positive


In [ ]:
x=int(input('enter a number '))
x=int(x)
if(x>0):
    print('Positive',x)
elif(x<0):
    print('Negative',x)
else:
    print("Zero",x)    
    
    print('Thank you')

enter a number 28
Positive 28


In [ ]:
year=int(input('enter a year '))
if(year%400==0) and (year%100==0):
    print('{0} is leap year'.format(year))
elif(year%4==0) and (year%100!=0):
    print('{0} is a leap year'.format(year))
else:
    print("{0} is not a leap year".format(year))    


enter a year 2100
2100 is not a leap year


In [ ]:
num1=float(input('enter a number'))
num2=float(input('enter a number'))
num3=float(input('enter a number'))
if(num1>=num2) and (num1>=num3):
    largest=num1
elif(num2>=num3):
    largest=num2
else:
    largest = num3
    
print("Largest=", largest)

enter a number4
enter a number5
enter a number6
Largest= 6.0


In [ ]:
x=int(input('enter a number '))
if(x%5==0)and(x%3==0):
    print('Divisible',x)
else:
    print("Not",x)    


enter a number 15
Divisible 15


In [ ]:
a=int(input('enter first side '))
b=int(input('enter second side '))
c=int(input('enter third side '))
if(a+b>c)and(b+c>a)and(c+a>b):
    print("Possible")
else:
    print("Not")

enter first side 4
enter second side 5
enter third side 6
Possible


In [ ]:
my_list=[1,2,3]
print(my_list)

[1, 2, 3]


In [ ]:
my_list=[1,"Hello",3.4]
print(my_list)

[1, 'Hello', 3.4]


In [ ]:
my_list=[1,"Hello",3.4]
print(my_list[1])

Hello


In [ ]:
my_list=["Hello",[2,0,1,5]]
print(my_list[1][3])
print(my_list[1][-3])
print(my_list[1:2])
print(my_list[:-1])
print(my_list[1:])
my_list[1]=1
print(my_list)
my_list[0:1]=[2,3]
print(my_list)
my_list[0:2]=[4,5,7]
print(my_list)
my_list[1:3]=[8,9,6]
print(my_list)
my_list[4]=6
print(my_list[::-1])#reverse list

5
0
[[2, 0, 1, 5]]
['Hello']
[[2, 0, 1, 5]]
['Hello', 1]
[2, 3, 1]
[4, 5, 7, 1]
[4, 8, 9, 6, 1]
[6, 6, 9, 8, 4]


In [ ]:
x=[1,2,3,4,5]
x.append('hello')
x.append(27)
x.append(430.5)
x.extend([8,9,7])
for k in x:
    print(k)

1
2
3
4
5
hello
27
430.5
8
9
7


In [ ]:
odd=[1,3,5]
print(odd+[2,4,6])
print(odd*3)
print(["xyz"]*10)
del odd[2:3]
print(odd)
print(odd.pop(1))
print(odd)

[1, 3, 5, 2, 4, 6]
[1, 3, 5, 1, 3, 5, 1, 3, 5]
['xyz', 'xyz', 'xyz', 'xyz', 'xyz', 'xyz', 'xyz', 'xyz', 'xyz', 'xyz']
[1, 3]


In [ ]:
odd=[1,3,5]
print(odd.pop(1))
print(odd)
print(odd.clear())

3
[1, 5]
None


In [ ]:
vowels=['a','i','e','u','o']
vowels.sort()
print(vowels)
vowels.sort(reverse=True)
print(vowels)

['a', 'e', 'i', 'o', 'u']
['u', 'o', 'i', 'e', 'a']


In [ ]:
vowels=['a','i','e','u','o','i']
print(sorted(vowels))
index=vowels.index('i')
print(index)
c=vowels.count('i')
print(c)
py='Python'
print(sorted(py))
names=["pat","cat","bat","hat","mat"]
print(sorted(names,reverse=True))
vowels1=vowels.copy()
vowels1.append('dog')
print(vowels)
print(vowels1)
print(len(vowels))

['a', 'e', 'i', 'i', 'o', 'u']
1
2
['P', 'h', 'n', 'o', 't', 'y']
['pat', 'mat', 'hat', 'cat', 'bat']
['a', 'i', 'e', 'u', 'o', 'i']
['a', 'i', 'e', 'u', 'o', 'i', 'dog']
6


In [ ]:
t1=(1,"hello",3.4,'p','r','o','g','r','a','m')
print(t1)
t2=("mouse",[8,4,6],(1,2,3))
print(t2[0][3])
t3=1,"hello",3.4 #tuple packing
print(t3[-1])
print(t1[1:4])
#a,b,c=t1
print(a)
print(b)
print(c)
print(t1.index('g'))
print('z' not in t1)

(1, 'hello', 3.4, 'p', 'r', 'o', 'g', 'r', 'a', 'm')
s
3.4
('hello', 3.4, 'p')
1
hello
3.4
6
True


In [ ]:
a=(2,3,4)
b=(2,3,4,7,89,87)
for x in b:
    if x in a:
        print('element present',x)
    else:
        print("element not present",x)

element present 2
element present 3
element present 4
element not present 7
element not present 89
element not present 87


In [ ]:
print((1,2,3)+(4,5,6))
t1=("Repeat","x")
t2=(1,2,3)
t3=t1+t2
print(t3)

(1, 2, 3, 4, 5, 6)
('Repeat', 'x', 1, 2, 3)


In [ ]:
for name in('John','Kate'):
    print("Hello",name)

Hello John
Hello Kate


In [ ]:
t1=(21,43,65)
print(all(t))
t=()
print(all(t1))
print(any(t1))
print(max(t1))
print(len(t1))
print(sum(t1))

True
True
True
65
3
129


In [ ]:
grocery=['bread','milk','butter']
enum=enumerate(grocery)
print(type(enum))
print(list(enum))
for count,item in enumerate(grocery,100):
    print(count,item)
for count,item in enumerate(grocery):
    print(count,item)

<class 'enumerate'>
[(0, 'bread'), (1, 'milk'), (2, 'butter')]
100 bread
101 milk
102 butter
0 bread
1 milk
2 butter


In [ ]:
list=[1,2,3,4]
t2=tuple(list)
print(t2)

(1, 2, 3, 4)


In [ ]:
num=int(input("enter number"))
st=str(input("enter your string "))
x = float(input("Enter a float number"))
lst = []
n = int(input("Enter number of elements : "))
for i in range(0, n):
    ele = int(input())  
    lst.append(ele) # adding the element      

print(num,":",st,":",x,":",lst)

enter number5
enter your string xyz
Enter a float number5.5
Enter number of elements : 4
3
4
5
6
5 : xyz : 5.5 : [3, 4, 5, 6]


In [ ]:
print("Armstrong Numbers Between 1 and 1000:")
first = 100
last = 1000
while first<=last:
  res = 0
  temp = first
  noOfDigit = 0
  while temp>0:
    temp = int(temp/10)
    noOfDigit = noOfDigit + 1
  num = first
  while num>0:
    rem = num%10
    pow = 1
    i = 0
    while i<noOfDigit:
      pow = pow*rem
      i = i+1
    res = res+pow
    num = int(num/10)
  if res == first:
    print(res)
  first = first+1

Armstrong Numbers Between 1 and 1000:
153
370
371
407


In [ ]:
n = int(input("Enter the value of 'n': "))
a = 3
b = 8
sum = 13
count = 1
print("Fibonacci Series: ", end = " ")
while(count <= n): 
  print(sum, end = " ")
  count += 1
  a = b
  b = sum
  sum = a + b


Enter the value of 'n': 10
Fibonacci Series:  13 21 34 55 89 144 233 377 610 987 

In [ ]:
a=[]
n=int(input("Enter number of elements:"))
for i in range(1,n+1):
    b=int(input("Enter element:"))
    a.append(b)
even=[]
odd=[]
for j in a:
    if(j%2==0):
        even.append(j)
    else:
        odd.append(j)
print("The even list",even)
print("The odd list",odd)

In [ ]:
pi=int(input('enter product id '))
cp=int(input('enter product name '))
sp=int(input('enter sale price '))
u=int(input('enter units '))


In [ ]:
def printme(str):
    "this prints a passing string function"
    print(str)
    return
printme("hello..first call to udf")
printme("second call to udf")
printme("third call to udf")

hello..first call to udf
second call to udf
third call to udf


In [ ]:
printme("third call to udf")
# all parameters in python language are passed by reference

third call to udf


In [ ]:
def changename(any_list):
    list1=[1,2,3,4]
    print("values inside the function:", list1)
    return 
list1=[10,20,39]
changename(list1);
print("values outside the function:",list1)

values inside the function: [1, 2, 3, 4]
values outside the function: [10, 20, 39]


In [ ]:
list1=[10,20,39]
def changename(any_list):
    any_list.append([1,2,3,4])
    print("values inside the function:", any_list)
    return 
changename(list1);
print("values outside the function:",list1)

In [ ]:
def printme(str):
    "this prints a passing string function"
    print(str)
    return
printme(str="my string")

my string


In [ ]:
def printme(name,age=35):
    "Test function"
    print("name:",name);
    print("age=",age);
    return;
printme(age=50, name="xyz");
printme(name="xyz");

name: xyz
age= 50
name: xyz
age= 35


In [ ]:
def printme(*vartuple):
    "Test function"
    print("output is:");
    for var in vartuple:
        print(var)
    return;
printme(10);
printme(10,70,60,50,"hello");

output is:
10
output is:
10
70
60
50
hello


In [ ]:
def calc(*vartuple):
    pro=1
    sum=0
    for var in vartuple:
        sum=sum+var
        pro*=var
    return(sum,pro)

def main():
    [s,p]=calc(10,20,30,40,50)
    print("sum=",sum)
    print("product=",pro)
    return
main()

sum= <built-in function sum>


NameError: name 'pro' is not defined

In [ ]:
def calc(*vartuple):
    pro=1
    sum=0
    for var in vartuple:
        sum+=var
        pro*=var
    return(sum,pro)

def main():
    [s1,p]=calc(10,20,30,40,50)
    print("sum=",s1)
    print("product=",p)
    return
main()

sum= 150
product= 12000000


In [ ]:
def calc(x,y):
    pro=1
    sum=0
    sub=0
    div=0
    sum=x+y
    pro=x*y
    sub=x-y
    div=x/y
    return(sum,sub,pro,div)

def main():
    [s,st,p,d]=calc(20,5)
    print("sum=",s)
    print("product=",p)
    print("difference=",st)
    print("ratio=",d)
    return
main()

sum= 25
product= 100
difference= 15
ratio= 4.0


In [ ]:
def func(**kwargs):
    for key, value in kwargs.items():
        print("%s = %s" %(key, value))
print("\nResult of **kwargs")
func(name='xyz', info='your age', age=30)


Result of **kwargs
name = xyz
info = your age
age = 30


In [ ]:
sum=lambda arg1,arg2:arg1+arg2;
print("value of total:",sum(10,20))
print("value of total:",sum(20,20))

value of total: 30
value of total: 40


In [ ]:
sum=lambda arg1,arg2 : arg1**2 + arg1*2 + arg2;
print("value of total:",sum(10,20))
print("value of total:",sum(20,20))

value of total: 140
value of total: 460


In [ ]:
#PASS A LIST IN A FUNCTION AND FIND THE SUM, MAX,MIN VALUE OF THE NUMERIC ELEMENTS IN IT
def listfunc(lst):
    # Calculate sum of elements
    sum = 0
    for i in lst:
        sum += i

    # Find max value
    max1 = lst[0]
    for i in lst:
        if i > max1:
            max1 = i

    # Find min value
    min1 = lst[0]
    for i in lst:
        if i < min1:
            min1 = i

    # Return results as a tuple
    return (sum, max1, min1)

def main():
    list1=[5,10,15,20,25]
    result=listfunc(list1)
    print(result)
main()
    

(75, 25, 5)


In [ ]:
#PASS A NUMBER AND FIND THE FACTORIAL VALUE USING FUNCTION
def fact(n):
    if n==0:
        return 1
    else:
        return n*fact(n-1)

def main():
    result=fact(5)
    print(result)
    
main()

120


In [ ]:
#PASS A LIST IN A FUNCTION AND RETURN THE SORTED LIST
def sort_list(my_list):
    n = len(my_list)
    for i in range(n):
        for j in range(i+1, n):
            if my_list[i] > my_list[j]:
                my_list[i], my_list[j] = my_list[j], my_list[i]
    return my_list

my_list = [5, 2, 8, 1, 9]
sorted_list = sort_list(my_list)
print(sorted_list)

[1, 2, 5, 8, 9]


In [ ]:
#PASS A TUPLE AND FIND THE MAXIMUM AND MINIMUM VALUE IN IT
def get_max_min(my_tuple):
    
    max_val = my_tuple[0]
    min_val = my_tuple[0]
    
    for val in my_tuple:
        if val > max_val:
            max_val = val
        elif val < min_val:
            min_val = val
    
    return (max_val, min_val)

my_tuple = (5, 2, 8, 1, 9)
max_val, min_val = get_max_min(my_tuple)
print("Maximum value:", max_val)
print("Minimum value:", min_val)

Maximum value: 9
Minimum value: 1


In [ ]:
#pass two numeric list in the function and find the sum and average of all elements in the list in python
def get_sum_avg(list1, list2):
    # Calculate the sum of all elements in the two lists
    total_sum = sum(list1) + sum(list2)
    
    # Calculate the average of all elements in the two lists
    total_count = len(list1) + len(list2)
    total_avg = total_sum / total_count
    
    # Return a tuple containing the sum and average values
    return (total_sum, total_avg)

list1 = [5, 2, 8, 1, 9]
list2 = [3, 7, 6, 4, 5]
total_sum, total_avg = get_sum_avg(list1, list2)
print("Total sum:", total_sum)
print("Total average:", total_avg)

Total sum: 50
Total average: 5.0


In [ ]:
#input a set and return the sorted list when passed through a function
def sort_set(my_set):
    # Convert set to list and sort it
    sorted_list = sorted(list(my_set))
    
    # Return sorted list
    return sorted_list

my_set = {5, 2, 8, 1, 9}
sorted_list = sort_set(my_set)
print(sorted_list)

[1, 2, 5, 8, 9]


In [ ]:
#pass two lists in a function and get their concatenated list
def concat_lists(list1, list2):
    return list1 + list2
list1 = [1, 2, 3]
list2 = [4, 5, 6]
concatenated_list = concat_lists(list1, list2)
print(concatenated_list)

[1, 2, 3, 4, 5, 6]


In [ ]:
#pass a dictionary and return its keys and values in separate lists
def separate_dict(d):
    keys = []
    values = []
    for key in d:
        keys.append(key)
        values.append(d[key])
    return keys, values

my_dict = {'apple': 1, 'banana': 2, 'orange': 3}
keys, values = separate_dict(my_dict)
print(keys)  
print(values)

['apple', 'banana', 'orange']
[1, 2, 3]


In [ ]:
#WRITE A FUNCTION TO CHECK WHETHER A NUMBER IS PALINDRIOME OR NOT 
def is_palindrome(num):
    num_str = str(num)
    return num_str == num_str[::-1]

print(is_palindrome(12321))
print(is_palindrome(12345))

True
False


In [ ]:
#WRITE A FUNCTION TO GENERATE FIBONACCI NUMBERS BELOW 1000
def generate_fibonacci():
    fib = [1, 1]
    while fib[-1] < 1000:
        next_fib = fib[-1] + fib[-2]
        fib.append(next_fib)
    return fib[:-1]
fib = generate_fibonacci()
print(fib)

[1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987]


In [ ]:
#WRITE A FUNCTION TO GENERATE PRIME NUMBERS BELOW 100
def generate_primes():
    primes = []
    for num in range(2, 100):
        is_prime = True
        for i in range(2, int(num ** 0.5) + 1):
            if num % i == 0:
                is_prime = False
                break
        if is_prime:
            primes.append(num)
    return primes

primes = generate_primes()
print(primes)

[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97]


In [ ]:
#RETURN THE ROOT OF A QUADRATIC EQUATION BY SUPPLYING THE VALUE OF PARAMETERS A,B,C.
def find_roots(a, b, c):
    discriminant = b**2 - 4*a*c
    if discriminant < 0:
        return "No real roots"
    elif discriminant == 0:
        return -b / (2*a)
    else:
        root1 = (-b + discriminant**0.5) / (2*a)
        root2 = (-b - discriminant**0.5) / (2*a)
        return root1, root2
    
print(find_roots(1, 5, 6))

(-2.0, -3.0)


In [ ]:
x=int(input("enter x:"))
n=int(input("enter n:"))
def series(x,n):
    sum=0
    if x == 1:
        return n
    else:
        for i in range(1,n+1):
            sum=sum+x**i
    return sum
s=series(x,n)  
print(s)

enter x2
enter n3
14


In [ ]:
x=int(input("enter x:"))
n=int(input("enter n:"))
def series(x,n):
    sum=0
    if x == 1:
        return n
    else:
        for i in range(1,n+1):
            sum=sum+1/(x**i)
    return sum+x
s=series(x,n)  
print(s)

enter x:2
enter n:2
2.75


In [ ]:
import math
x=int(input("enter x:"))
n=int(input("enter n:"))
def fact(x, n):
    result = x  # initialize result with x
    factorial = 1  # initialize factorial with 1
    for i in range(1, n+1):
        factorial *= i  # compute factorial(i)
        result += x / factorial  # add x/i! to the result
        x /= (x+i)  # update x for the next iteration
    return result
f=fact(x,n)
print(f)

enter x:1
enter n:4
2.2859374999999997


In [ ]:
import array as arr
array1=arr.array('d',[])
for x in range(10):
    array1.append(x)
    
for x in array1:
    print(x)

0.0
1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0
9.0


In [ ]:
#importing "array" for array operations

import array

#initializing array with array values

arr= array.array('i',[1,2,3])

#printing original array

print("The new created array is:",end=" ")
for i in range(0,3):
    print(arr[i],end=" ")
print("\r")

#using append() to insert new value at end

arr.append(4);

#printing appended array

print("The appended array is:",end="")
for i in range(0,4):
    print(arr[i],end=" ")
    
#using insert() to insert value at specific position
#insert 5 at 2nd position

arr.insert(2,5)

#printing array after insertion

print("The array after insertion is:", end="")
for i in range(0,5):
    print(arr[i],end=" ")

The new created array is: 1 2 3 
The appended array is:1 2 3 4 The array after insertion is:1 2 5 3 4 

In [ ]:
import array

#initializing array with array values
#initializing array with signed integers

arr=array.array('i',[1,2,3,1,5])

#printing original array

print("The new created array is:", end="")
for i in range(0,5):
    print(arr[i],end=" ")

#using pop() to remove element at 2nd position

print("The popped element is:",end="")
print(arr.pop(2));

#printing array after popping

print("The array after popping is",end="")
for i in range(0,4):
    print(arr[i],end=" ")
print("\r")

#using remove() to remove 1st occurance of 1

arr.remove(1)

# printing array after removing

print("The array after removing is:", end="")
for i in range(0,3):
    print(arr[i],end=" ")

The new created array is:1 2 3 1 5 The popped element is:3
The array after popping is1 2 1 5 
The array after removing is:2 1 5 

In [ ]:
import array
arr=array.array('i',[1,2,3,1,2,5])
print("The new created arrat is:", end=" ")
for i in range(0,6):
    print(arr[i],end=" ")
print("\n")
print("The index of 1st occurance of 2 is:",end=" ")
print(arr.index(2))

The new created arrat is: 1 2 3 1 2 5 

The index of 1st occurance of 2 is: 1


In [ ]:
import array
arr=array.array('i',[1,2,3,1,2,5])
print("The new created array is:", end="")
for i in range (0,6):
    print(arr[i],end=" ")
print("\r")
arr.reverse()
print("The array after reversing is:")
for i in range (0,6):
    print(arr[i],end=" ")

The new created array is:1 2 3 1 2 5 
The array after reversing is:
5 2 1 3 2 1 

In [ ]:
from array import*
array_num=array('i',[1,3,5,7,9])
print("Type code of an array is:", array_num.typecode)

Type code of an array is: i


In [ ]:
from array import*
array_num=array('i',[1,3,5,7,9,10,15])
print("The number of bytes hold by each element:", array_num.itemsize)

The number of bytes hold by each element: 4


In [ ]:
from array import*
array_num=array('i',[1,3,5,7,9,10,15])
print("The buffer information :", array_num.buffer_info())

The buffer information : (1897559025328, 7)


In [ ]:
from array import*
array_num=array('i',[1,3,5,7,9,10,15,10])
print("The number of occurance of element 10:", array_num.count(10))

The number of occurance of element 10: 2


In [ ]:
from array import*
array_num=array('i',[1,3,5,7,9])
array_num1=array('i',[2,4,6,8,10])
print("Original array:"+str(array_num))
array_num.extend(array_num1)
print("Entended array:"+str(array_num))

Original array:array('i', [1, 3, 5, 7, 9])
Entended array:array('i', [1, 3, 5, 7, 9, 2, 4, 6, 8, 10])


In [ ]:
from array import*
nums=array("i",[1,2])
lst=[23,33,44,55,66,77]
nums.fromlist(lst)
print(nums)

array('i', [1, 2, 23, 33, 44, 55, 66, 77])


In [ ]:
from array import*
array_num=array('i',[1,3,5,7,9])
print("Array to list:", array_num.tolist())

Array to list: [1, 3, 5, 7, 9]


In [ ]:
#to sort an array

import array as arr
array1=arr.array('d',[103.32,20.32,32,30,4.320,50.30])
for x in array1:
    print(x)
y=array1.tolist()
y.sort()
print(y)
y.sort(reverse=True)
print(y)

103.32
20.32
32.0
30.0
4.32
50.3
[4.32, 20.32, 30.0, 32.0, 50.3, 103.32]
[103.32, 50.3, 32.0, 30.0, 20.32, 4.32]


In [ ]:
A=[[1,4,5],[-5,8,9]]
for i in range(2):
    for j in range(3):
        print(A[i][j],end=" ")
    print("\n")

1 4 5 

-5 8 9 



In [ ]:
n=3
m=4
a=[0]*n
for i in range(n):
    a[i]=[0]*m
    print(a[i])

[0, 0, 0, 0]
[0, 0, 0, 0]
[0, 0, 0, 0]


In [ ]:
w,h=8,5;
MyMatrix=[[0 for x in range(w)] for y in range(h)]
for i in range(5):
    print(MyMatrix[i])

[0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0]


In [ ]:
n=int(input("Enter the number of rows in a matrix"))
a=[[0 for x in range(n)] for y in range(n)]
for i in range(n):
    for j in range(n):
        a[i][j]=int(input())
    print("\n")
    print(a)

Enter the number of rows in a matrix3
3
5
6


[[3, 5, 6], [0, 0, 0], [0, 0, 0]]
5
6
7


[[3, 5, 6], [5, 6, 7], [0, 0, 0]]
8
9
6


[[3, 5, 6], [5, 6, 7], [8, 9, 6]]


In [ ]:
n=int(input("Enter the number of rows in a matrix"))
a=[[0 for x in range(n)] for y in range(n)]
for i in range(n):
    for j in range(n):
        a[i][j]=int(input())
    print("\n")

    for i in range(n):
        print(a[i])

Enter the number of rows in a matrix2
2
2


[2, 2]
[0, 0]
2
2


[2, 2]
[2, 2]


In [ ]:
n=int(input("Enter the number of rows in a matrix"))
a=[[0 for x in range(n)] for y in range(n)]
for i in range(n):
    for j in range(n):
        a[i][j]=int(input())
    print("\n")

    for i in range(n):
        print(a[i])

Enter the number of rows in a matrix2
3
4


[3, 4]
[0, 0]
5
6


[3, 4]
[5, 6]


In [ ]:
print("Enter row and column")
r=int(input("Enter the number of rows in a matrix"))
c=int(input("Enter the number of column in a matrix"))
a=[[int(input())for x in range(c)] for y in range(r)]
for i in range(r):
    for j in range(c):
        print(a[i][j],end=' ')
    print()

Enter row and column
Enter the number of rows in a matrix2
Enter the number of column in a matrix2
22
2
2
2
22 2 
2 2 


In [ ]:
print("Enter row and column")
r=int(input("Enter the number of rows in a matrix"))
c=int(input("Enter the number of column in a matrix"))
a=[[int(input())for x in range(c)] for y in range(r)]
for i in range(r):
    for j in range(c):
        print(a[i][j],end=' ')
    print()

Enter row and column
Enter the number of rows in a matrix2
Enter the number of column in a matrix2
2
3
4
5
2 3 
4 5 


In [ ]:
x=[[12,7,3],
   [4,5,6],
   [7,8,9]]
y=[[5,8,1],
   [6,7,3],
   [4,5,9]]
result=[[0,0,0],
        [0,0,0],
        [0,0,0]]
for i in range(len(x)):
    for j in range(len(x[0])):
        result[i][j]=x[i][j]+y[i][j]
for r in result:
    print(r)

[17, 15, 4]
[10, 12, 9]
[11, 13, 18]


In [ ]:
print("Enter row and column")
r=int(input("Enter the number of rows in a matrix"))
c=int(input("Enter the number of column in a matrix"))
a=[[int(input())for x in range(c)] for y in range(r)]
print("Matrix elements are")
for i in range(r):

    for j in range(c):
        print(a[i][j],end=' ')
    print()
    

Enter row and column
Enter the number of rows in a matrix2
Enter the number of column in a matrix1
3
4
Matrix elements are
3 
4 


In [ ]:
#to sort an array

import array as arr
array1=arr.array('d',[103.32,20.32,32,30,4.320,50.30])
for x in array1:
    print(x)
y=array1.tolist()
y.sort()
print(y)
y.sort(reverse=True)
print(y)

103.32
20.32
32.0
30.0
4.32
50.3
[4.32, 20.32, 30.0, 32.0, 50.3, 103.32]
[103.32, 50.3, 32.0, 30.0, 20.32, 4.32]


In [ ]:
A=[[1,4,5],[-5,8,9]]
for i in range(2):
    for j in range(3):
        print(A[i][j],end=" ")
    print("\n")

1 4 5 

-5 8 9 



In [ ]:
n=3
m=4
a=[0]*n
for i in range(n):
    a[i]=[0]*m
    print(a[i])

[0, 0, 0, 0]
[0, 0, 0, 0]
[0, 0, 0, 0]


In [ ]:
w,h=8,5;
MyMatrix=[[0 for x in range(w)] for y in range(h)]
for i in range(5):
    print(MyMatrix[i])

[0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0]


In [ ]:
n=int(input("Enter the number of rows in a matrix"))
a=[[0 for x in range(n)] for y in range(n)]
for i in range(n):
    for j in range(n):
        a[i][j]=int(input())
    print("\n")
    print(a)

Enter the number of rows in a matrix2
2



ValueError: invalid literal for int() with base 10: ''

In [ ]:
n=int(input("Enter the number of rows in a matrix"))
a=[[0 for x in range(n)] for y in range(n)]
for i in range(n):
    for j in range(n):
        a[i][j]=int(input())
    print("\n")
    print(a)
    

Enter the number of rows in a matrix2
1
1


[[1, 1], [0, 0]]
2
3


[[1, 1], [2, 3]]


In [ ]:
n=int(input("Enter the number of rows in a matrix"))
a=[[0 for x in range(n)] for y in range(n)]
for i in range(n):
    for j in range(n):
        a[i][j]=int(input())
    print("\n")

    for i in range(n):
        print(a[i])

Enter the number of rows in a matrix2
1
1


[1, 1]
[0, 0]
1
1


[1, 1]
[1, 1]


In [ ]:
print("Enter row and column")
r=int(input("Enter the number of rows in a matrix"))
c=int(input("Enter the number of column in a matrix"))
a=[[int(input())for x in range(c)] for y in range(r)]
for i in range(r):
    for j in range(c):
        print(a[i][j],end=' ')
    print()

Enter row and column
Enter the number of rows in a matrix2
Enter the number of column in a matrix2
1
1
1
1
1 1 
1 1 


In [ ]:
x=[[12,7,3],
   [4,5,6],
   [7,8,9]]
y=[[5,8,1],
   [6,7,3],
   [4,5,9]]
result=[[0,0,0],
        [0,0,0],
        [0,0,0]]
for i in range(len(x)):
    for j in range(len(x[0])):
        result[i][j]=x[i][j]+y[i][j]
for r in result:
    print(r)

[17, 15, 4]
[10, 12, 9]
[11, 13, 18]


In [ ]:
# file handling
f=open("a.txt",'w')
line1='Welcome to python.'
f.write(line1)
line2="\nRegularly working in python"
f.write(line2)
f.close()
f=open("a.txt",'r')
text=f.read()
print(text)
f.close()

Welcome to python.
Regularly working in python


In [ ]:
print("Enter row and column")
r=int(input("Enter the number of rows in a matrix"))
c=int(input("Enter the number of column in a matrix"))
a=[[int(input())for x in range(c)] for y in range(r)]
print("Matrix elements are")
for i in range(r):

    for j in range(c):
        print(a[i][j],end=' ')
    print()
    

In [ ]:
x=[[0,0,0],
   [0,0,0],
   [0,0,0]]
y=[[1,1,1],
   [1,1,1],
   [1,1,1]]
result=[[0,0,0],
        [0,0,0],
        [0,0,0]]
for i in range(len(x)):
    for j in range(len(x[0])):
        result[i][j]=x[i][j]+y[i][j]
for r in result:
    print(r)

In [ ]:
x=[[1,0,3],
   [1,2,0],
   [0,2,1]]
y=[[3,0,1],
   [0,2,3],
   [1,4,6]]
result=[[0,0,0],
        [0,0,0],
        [0,0,0]]
for i in range(len(x)):
    for j in range(len(x[0])):
        result[i][j]=x[i][j]*y[j][i]
for r in result:
    print(r)

In [ ]:
x=[[1,0,3],
   [1,2,0],
   [0,2,1]]
y=[[3,0,1],
   [0,2,3],
   [1,4,6]]
result=[[0,0,0],
        [0,0,0],
        [0,0,0]]
for i in range(len(x)):
    for j in range(len(x[0])):
        result[i][j]=x[i][j]*y[i][j]
for r in result:
    print(r)

In [ ]:
import numpy as np
a=np.arange(15)
print("The array is as follows:")
print(a)
b=a.reshape(3,5)
print("The new array is as follows:")
print(b)
a=np.arange(15).reshape(3,5)
print("The new array is as follows:")
print(a)

In [ ]:
np.linspace(0,2,9)

In [ ]:
np.linspace(0,1,20)

In [ ]:
import numpy as np
zeros_array=np.zeros((2,3),dtype=np.int64)
print(zeros_array)

In [ ]:
ones_array=np.ones((3,5),dtype=np.int32)
print(ones_array)

In [ ]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(arr)

In [ ]:
import numpy as np
list_1=[1,2,3,4]
list_2=[5,6,7,8]
list_3=[9,10,11,12]
sample_array=np.array([list_1,list_2,list_3])
print("Numpy array:")
print(sample_array)
print("Shape of the array:",sample_array.shape)

In [ ]:
import numpy as np
iterable=(a*a for a in range(8))
arr=np.fromiter(iterable,float)
print("array is:",arr)

In [ ]:
import numpy as np
arr= np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('2nd element on 1st dim:',arr[0,1])
print('5th element on 2nd dim:',arr[1,4])

In [ ]:
import numpy as np
in_arr1=np.array([[2,-7,5],[-6,2,0]])
in_arr2=np.array([[5,8,-5],[3,6,9]])
print("1st input array:",in_arr1)
print("2nd input array:",in_arr2)
out_arr=np.add(in_arr1,in_arr2)
print("output added array:",out_arr)

In [ ]:
import numpy 
x=numpy.array([[1,2],[4,5]])
y=numpy.array([[7,8],[9,10]])
print("Addition of two matrices:")
print(numpy.add(x,y))
print("Subtraction of two matrices:")
print(numpy.subtract(x,y))
print("Matrix Division:")
print(numpy.divide(x,y))
print("Multiplication of two matrices:")
print(numpy.multiply(x,y))
print("The Product of two matrices:")
print(numpy.dot(x,y))

In [ ]:
import numpy 
x=numpy.array([[1,2],[4,5]])
y=numpy.array([[7,8],[9,10]])
print("Square root is:")
print(numpy.sqrt(x))
print("The summation of elements:")
print(numpy.sum(y))
print("The column wise summation:")
print(numpy.sum(y,axis=0))
print("The row wise summation:")
print(numpy.sum(y,axis=1))

In [ ]:
import numpy as np
np.random.uniform(1,10,size=10)

In [ ]:
import numpy as np
np.random.uniform(size=5)

In [ ]:
import numpy as np
np.random.uniform(size=(2,3))
print (np.random.uniform(size=(2,3)))

In [ ]:
import numpy as np
np.random.randint(1,20,size=(4,3))

In [ ]:
import numpy as np
np.random.randint(1,20,size=10)

In [ ]:
import numpy as np
a=np.full([2,3],23,dtype=int)
print(a)

In [ ]:
import numpy as np
arr=np.random.randint(1,20,size=30)
print(arr)
np.unique(arr)

In [1]:
import numpy as np
arr=np.random.randint(1,20,size=(8,3))
print(arr)
np.unique(arr,return_index=True)

[[ 2  1 18]
 [ 3 12 17]
 [18 17 11]
 [17 12  3]
 [17  6 19]
 [15  9  5]
 [ 1 12  3]
 [11 17 19]]


(array([ 1,  2,  3,  5,  6,  9, 11, 12, 15, 17, 18, 19]),
 array([ 1,  0,  3, 17, 13, 16,  8,  4, 15,  5,  2, 14]))

In [ ]:
import numpy as np
arr=np.random.randint(1,20,size=(8,3))
print(arr)
np.unique(arr,return_index=True,return_counts=True)

In [ ]:
import numpy as np
a=np.identity(3)
print("The identity Matrix:\n",a)

In [ ]:
import numpy as np
a=np.arange(15).reshape(3,5)
print(a)
a=a[np.where(a>5)]
print("array elements larger than 5:\n",a)

In [ ]:
import numpy as np
a=np.arange(15).reshape(3,5)
print(a)
a=a[np.where(a<5)]
print("array elements larger than 5:\n",a)

In [ ]:
import numpy as np
a=np.arange(24)
print(a)
print("\n")
print("Size of array",a.size)
print("shape of array:",a.shape)
print("The above array is{0} dimensional".format(a.ndim))
x=a.reshape(4,6)
print(x)
print("\n")
print("Size of array",x.size)
print("shape of array:",x.shape)
print("The above array is{0} dimensional".format(x.ndim))
print("\n")
b=a.reshape(2,4,3)
print(b)
print("\n")
print("Size of array",b.size)
print("shape of array:",b.shape)
print("The above array is{0} dimensional".format(b.ndim))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


Size of array 24
shape of array: (24,)
The above array is1 dimensional
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


Size of array 24
shape of array: (4, 6)
The above array is2 dimensional


[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


Size of array 24
shape of array: (2, 4, 3)
The above array is3 dimensional


In [ ]:
import numpy as np
arr=np.array([[5,6],[7,8]])
x=arr.ravel()
print("")

In [ ]:
import numpy as np
a=np.array([(1,2,3,4),(3,1,4,2)])
print("Original array:\n",a)
c=a.flatten()
print("\nFlatten array using flatten:",c)
c[2]=37
print("Flatten array:",c)
print("\n Original array:\n",a)

Original array:
 [[1 2 3 4]
 [3 1 4 2]]

Flatten array using flatten: [1 2 3 4 3 1 4 2]
Flatten array: [ 1  2 37  4  3  1  4  2]

 Original array:
 [[1 2 3 4]
 [3 1 4 2]]


In [ ]:
import numpy as np
a=np.array([(1,2,3,4),(3,1,4,2)])
print("Original array:\n",a)
ra=a.flatten()
print("\nFlatten array using flatten:",c)
c[2]=37
print("Flatten array:",c)
print("\n Original array:\n",a)

Original array:
 [[1 2 3 4]
 [3 1 4 2]]

Flatten array using flatten: [ 1  2 37  4  3  1  4  2]
Flatten array: [ 1  2 37  4  3  1  4  2]

 Original array:
 [[1 2 3 4]
 [3 1 4 2]]


In [ ]:
# file handling
f=open("a.txt",'w')
line1='Welcome to python.'
f.write(line1)
line2="\nRegularly working in python"
f.write(line2)
f.close()
f=open("a.txt",'r')
text=f.read()
print(text)
f.close()

Welcome to python.
Regularly working in python


In [ ]:
file1=open("myfile.txt","w")
L=["This is Delhi\n","This is Paris\n","This is London\n"]
file1.writelines(L)
file1.close()
f=open("myfile.txt",'r')
text=f.read()
print(text)
f.close()

This is Delhi
This is Paris
This is London



In [ ]:
f=open("a.txt","r+")
print("name:",f.name)
line=f.readline()
print("Read line: %s"%(line))
line=f.readline(5)
print("Read line: %s"%(line))
f.close()

name: a.txt
Read line: Welcome to python.

Read line: Regul


In [ ]:
f=open("sample.txt","rb")
f.seek(-10,2)
print(f.tell())
print(f.readline().decode('utf-8'))
f.close()

FileNotFoundError: [Errno 2] No such file or directory: 'sample.txt'

In [ ]:
fruits=["apple\n", "orange\n", "grapes\n", "watermelon\n", "banana\n"]
my_file=open("test.txt","w")
my_file.writelines(fruits)
my_file.close()
#to read the file
f=open("test.txt", 'r')
print(f.read())
print()
f.seek(0)
# to read the lines
for line in f:
    print(line,end="")
print()
print()

#to read a particular line
#specific package to catch a line
import linecache
#extracting the 4th line
particular_line=linecache.getline('test.txt',4)
#print the particular line
print(particular_line)
f.close()

apple
orange
grapes
watermelon
banana


apple
orange
grapes
watermelon
banana


watermelon



In [ ]:
l=[12,33,44,55,66,77]
f=open("file1.bin",'wb')
for item in l:
    s=str(item)+"\n"
    bt=s.encode()
    f.write(bt)
f.close()
f=open("file1.bin",'rb')
for line in f:
    print(line)
    s=line.decode()
    print(s)
f.close()

b'12\n'
12

b'33\n'
33

b'44\n'
44

b'55\n'
55

b'66\n'
66

b'77\n'
77



In [ ]:
n=int(input("enter no of records"))
f=open("filerec.bin",'wb')
for i in range(n):
    roll=input("enter roll")
    name=input("enter name")
    age=input("enter age")
    mark=input("enter mark")
    s=roll+"\t"+name+"\t"+age+"\t"+mark+"\n"
    bt=s.encode()
    f.write(bt)
f.close()
f=open("filerec.bin",'rb')
for line in f:
    print(line)
    s=line.decode()
    print(s)
f.close()